RealProject2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^login/', include('login.urls')),
    url(r'^homepage/', include('homepage.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('login.urls')),
    
]

login/urls.py
from django.conf.urls import url

from . import views

app_name = "login"

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'dologin/$', views.dologin, name = "dologin"),
    url(r'doregister/$', views.doregister, name = "doregister"),
    url(r'register/$', views.register, name = "register"),
  
]

login/models.py
from django.db import models
from django.contrib.auth.models import User

class NewUser(User):
    isOnline = models.BooleanField(default = False)
    friends = models.ManyToManyField("self")
    picture = models.CharField(max_length=200, default="homepage/images/profilepic.png")
    score = models.IntegerField(default=0)
    
    def __str__(self):
        return self.username+";"+self.password

class Course(models.Model):
    course_name = models.CharField(max_length=200)
    num_of_lessons = models.IntegerField(default=0)
    image = models.CharField(max_length=200, default="")
    level = models.CharField(max_length=200, default="")
    #Quickreference sheet
    #gif library
    def __str__(self):
        return self.course_name+";"+str(self.num_of_lessons)

class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lesson_name = models.CharField(max_length=200)
    content = models.CharField(max_length=200)
    summary = models.TextField(default="")
    expected_output = models.CharField(max_length=200, default="")
    point_value = models.IntegerField(default=10)
    error_message = models.TextField(default="")
    #video
    def __str__(self):
        return self.course.course_name+";"+self.lesson_name

class Progress(models.Model):
    newuser = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)
    progress_until_now = models.TextField(default="")
    notes = models.TextField(default="")
    
    def __str__(self):
        return  str(self.id) + ";" + self.newuser.username+";"+self.progress_until_now

class Challenge(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    challenge_name = models.CharField(max_length=200)
    content = models.CharField(max_length=200)
    expected_output = models.CharField(max_length=200, default="")
    point_value = models.IntegerField(default=20)
    error_message = models.TextField(default="")
    
    def __str__(self):
        return self.lesson.lesson_name+";"+self.challenge_name

class ChallengeProgress(models.Model):
    newuser = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)
    progress_until_now = models.TextField(default="")
    notes = models.TextField(default="")
    
    def __str__(self):
        return self.newuser.username+";"+self.progress_until_now

class CourseLocation(models.Model):
    newuser = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    islessonornot = models.BooleanField(default=False)
    whichone = models.CharField(max_length=200)

login/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import authenticate, login

from .models import NewUser, Course, Lesson, Progress, Challenge


def index(request):
    return render(request, 'login/index.html',{})

def dologin(request):
    username = request.POST['UserName']
    password = request.POST['PassWord']

    if len(username) > 30:
        return HttpResponseRedirect(reverse('login:index'))
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        a = NewUser.objects.get(username = username)
        request.session[str(a.username)] = "1"
        a.isOnline = True
        a.save()
        return HttpResponseRedirect(reverse('homepage:courseList',args = (request.POST["UserName"],)))
    else:
        return HttpResponseRedirect(reverse('login:index'))
    

    
def register(request):
    return render(request, 'login/register.html',{})


def doregister(request):
    try:
        user = NewUser.objects.get(username = request.POST["UserName"])
        return render(request, 'login/register.html',{"Already_exist":True,"Password_Not_Match":False})
    except NewUser.DoesNotExist:
        if len(request.POST["UserName"]) > 30:
            return HttpResponseRedirect(reverse('login:register'))
        for i in "/#?*+- ":
            if i in request.POST["UserName"]:
                return HttpResponseRedirect(reverse('login:register'))
        if request.POST["PassWord"] == request.POST["ConPassWord"]:
            user = NewUser.objects.create_user(username = request.POST["UserName"], password = request.POST["PassWord"])
            login(request, user)
            a = NewUser.objects.get(username = user.username)
            request.session[str(a.username)] = "1"
            a.isOnline = True
            a.save()
            return HttpResponseRedirect(reverse('homepage:courseList',args = (request.POST["UserName"],)))
        else:
            return render(request, 'login/register.html',{"Already_exist":False,"Password_Not_Match":True})

login/templates/login/index.html
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />

{% if Something_Wrong %}<p><strong>Something Wrong!</strong></p>{% endif %}
<head>
    <script>
        function enterField(fieldname){
            el = document.getElementById(fieldname);
            if (el.value == "User Name"){
                el.value = "";
                el.style.color = "black";
                el.style.fontStyle = "normal";
            } else if (el.value == ""){
                el.value = "User Name";
                el.style.color = "grey";
                el.style.fontStyle = "italic";
            }
        }

        function exitField(el){
            if (el.value == ""){
                el.value = "User Name";
                el.style.color = "grey";
                el.style.fontStyle = "italic";
            } else{
                el.style.color = "black";
                el.style.fontStyle = "normal";
            }
        }
        
        function enterPassField(el){ 
            if (el.value == "Password" && (el.type != "password")){
                el.type = "password";
                el.value = "";
                el.style.color = "black";
                el.style.fontStyle = "normal";
            }
        }

        function exitPassField(el){
            if (el.value == ""){
                el.value = "Password";
                el.type = "text";
                el.style.color = "grey";
                el.style.fontStyle = "italic";
            } 
        }
    </script>
</head>




<body class="background">
<div class="titleAthena">
    <h1 class="titleText"> ATHENA </h1>
</div>
    <form action="{% url 'login:dologin' %}" method="post">
    {% csrf_token %}
        <div class="logintable">
            <table align = "center">
            <tr>
            <td colspan="2"><img class="loginimage" src= "{% static 'login/images/welcome.png' %}"></td>
            </tr>
            <tr>
            <tr>
            <td colspan="2"><p class="text-white">Please Login:</p></td>
            </tr>
            <tr>
            <td colspan="2"><input class="username" id = "username" type="text" name="UserName" value="User Name" onfocus="enterField('username')" onblur="exitField(this)"></td>
            </tr>
            <tr>
            <td colspan="2"><input class="password" type="text" name="PassWord" value="Password" onfocus="enterPassField(this)" onblur="exitPassField(this)"></td>
            </tr>
            <tr>
            <td><input class="button" type="submit" value="Login" /></td>
            <td><a class="abutton" href="{% url 'login:register' %}">Sign Up</a></td>
            </tr>
            </table>
        </div>  
    </form>
    
    <!--<div class="tag_line">
        <p>The complete coding education program that stimulates community based development.</p>
    </div>-->
</body>  
<!--
User name: <input type="text" name="UserName" value="User Name"><br>
PassWord: <input type="text" name="PassWord" value="Password"><br>
<input type="submit" value="Login or SignUp" />
-->
</html>

login/templates/login/register.html
{% if Already_exist %}<p><strong>Please change a user name!</strong></p>{% endif %}
{% if Password_Not_Match %}<p><strong>PassWord Not Match</strong></p>{% endif %}
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}" />
<script type="text/javascript" src="{% static 'login/loginscripts.js' %}" ></script>

<body class="background">
<div class="titleAthena">
    <h1 class="titleText"> ATHENA </h1>
</div>
    <form action="{% url 'login:doregister' %}" method="post">
    {% csrf_token %}
        <div class="logintable">
            <table align = "center">
            <tr>
            <td colspan="2"><img class="loginimage" src= "{% static 'login/images/welcome.png' %}"></td>
            </tr>
            <tr>
            <td><input class="username" type="text" name="UserName" value="User Name" onfocus="enterField(this)" onblur="exitField(this)"></td>
            </tr>
            <tr>
            <td><input class="password" type="text" name="PassWord" value="Password" onfocus="enterPassField(this)" onblur="exitPassField(this)"></td>
            </tr>
            <tr>
            <td><input class="password" type="text" name="ConPassWord" value="Confirm Password" onfocus="enterPassField(this)" onblur="exitPassField(this)"></td>
            </tr>
            <tr>
            <td><input class="button" type="submit" value="Sign Up" /></td>
            </tr>
            </table>
        </div>
    </form>

</body>
<!--
User name: <input type="text" name="UserName" value="User Name"><br>
PassWord: <input type="text" name="PassWord" value="Password"><br>
<input type="submit" value="Login or SignUp" />
-->
</html>