RealProject2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^login/', include('login.urls')),
    url(r'^homepage/', include('homepage.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('login.urls')),
    
]

homepage/urls.py
from django.conf.urls import url

from . import views

app_name = "homepage"

urlpatterns = [
        url(r'keepnotes/(?P<username>[^/]+)/(?P<lessonname>[^/]+)/$', views.keepnotes, name = 'keepnotes'),
        url(r'chat/(?P<fromID>[^/]+)/(?P<fromName>[^/]+)/(?P<toID>[^/]+)/(?P<toName>[^/]+)$', views.chat, name = 'chat'),
        url(r'keepprogress/(?P<username>[^/]+)/(?P<lessonname>[^/]+)/$', views.keepprogress, name = 'keepprogress'),
        url(r'course/(?P<username>[^/]+)/(?P<coursename>[^/]+)/(?P<lessonname>[^/]+)/$', views.course, name = 'course'),
        url(r'otherprofile/(?P<fromWho>[^/]+)/(?P<toWho>[^/]+)/$', views.otherprofile, name = 'otherprofile'),
        url(r'profile/(?P<username>[^/]+)/$', views.profile, name = 'profile'),
        url(r'logoutuser/$',views.logoutuser, name = 'logoutuser'),
        url(r'courselist/(?P<username>[^/]+)/$', views.courseList, name = 'courseList'),
        url(r'challenge/(?P<username>[^/]+)/(?P<coursename>[^/]+)/(?P<lessonname>[^/]+)/(?P<challengename>[^/]+)$', views.challenge, name = 'challenge')
]

login/urls.py
from django.conf.urls import url

from . import views

app_name = "login"

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'dologin/$', views.dologin, name = "dologin"),
    url(r'doregister/$', views.doregister, name = "doregister"),
    url(r'register/$', views.register, name = "register"),
  
]

homepage/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models
from django.contrib.auth.models import User

class NewUser(User):
    isOnline = models.BooleanField(default = False)
    friends = models.ManyToManyField("self")
    picture = models.CharField(max_length=200, default="homepage/images/profilepic.png")
    score = models.IntegerField(default=0)
    
    def __str__(self):
        return self.username+";"+self.password

class Course(models.Model):
    course_name = models.CharField(max_length=200)
    num_of_lessons = models.IntegerField(default=0)
    image = models.CharField(max_length=200, default="")
    level = models.CharField(max_length=200, default="")
    #Quickreference sheet
    #gif library
    def __str__(self):
        return self.course_name+";"+str(self.num_of_lessons)

class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lesson_name = models.CharField(max_length=200)
    content = models.CharField(max_length=200)
    summary = models.TextField(default="")
    expected_output = models.CharField(max_length=200, default="")
    point_value = models.IntegerField(default=10)
    error_message = models.TextField(default="")
    #video
    def __str__(self):
        return self.course.course_name+";"+self.lesson_name

class Progress(models.Model):
    newuser = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)
    progress_until_now = models.TextField(default="")
    notes = models.TextField(default="")
    
    def __str__(self):
        return  str(self.id) + ";" + self.newuser.username+";"+self.progress_until_now

class Challenge(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    challenge_name = models.CharField(max_length=200)
    content = models.CharField(max_length=200)
    expected_output = models.CharField(max_length=200, default="")
    point_value = models.IntegerField(default=20)
    error_message = models.TextField(default="")
    
    def __str__(self):
        return self.lesson.lesson_name+";"+self.challenge_name

class ChallengeProgress(models.Model):
    newuser = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)
    progress_until_now = models.TextField(default="")
    notes = models.TextField(default="")
    
    def __str__(self):
        return self.newuser.username+";"+self.progress_until_now

class CourseLocation(models.Model):
    newuser = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    islessonornot = models.BooleanField(default=False)
    whichone = models.CharField(max_length=200)

homepage/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib.sessions.models import Session
from django.utils import timezone

from login.models import NewUser, Course, Lesson, Progress, Challenge, ChallengeProgress, CourseLocation

from random import shuffle
def get_all_logged_in_users():
    # Query all non-expired sessions
    # use timezone.now() instead of datetime.now() in latest versions of Django
    sessions = Session.objects.filter(expire_date__gte=timezone.now())
    uid_list = []

    # Build a list of user ids from that query
    for session in sessions:
        data = session.get_decoded()
        uid_list.append(data.get('_auth_user_id', None))

    # Query all logged in users based on id list
    return NewUser.objects.filter(id__in=uid_list)



def profile(request, username):
    if request.user.is_authenticated:
        context = {
            "UserName":request.user.username,
            "Progress":Progress.objects.filter(newuser__username=username),
            "CProgress":ChallengeProgress.objects.filter(newuser__username=username),
            "score": NewUser.objects.get(username=username).score,
            "picture": NewUser.objects.get(username=username).picture
            }
        return render(request, 'homepage/profile.html',context)
    else:
        #return HttpResponseRedirect(reverse('login:index'))
        return render(request, 'homepage/logout.html')

def otherprofile(request, fromWho, toWho):
    context = {
        "ToWhoName":toWho,
        "Progress":Progress.objects.filter(newuser__username=toWho),
        "CProgress":ChallengeProgress.objects.filter(newuser__username=toWho),
        "FromWhoName":fromWho
        }
    return render(request, 'homepage/otherprofile.html', context)
    

def logoutuser(request):
    a = NewUser.objects.get(username = request.user.username)
    a.isOnline = False
    a.save()
    logout(request)
    return HttpResponseRedirect(reverse('login:index'))

def courseList(request, username):
    whosOnline = get_all_logged_in_users()
    lessonP10 = Progress.objects.filter(is_complete=True)
    challengeP10 = ChallengeProgress.objects.filter(is_complete=True)
    news = []
    for i in lessonP10:
        news.append(i)
    for i in challengeP10:
        news.append(i)
    shuffle(news)
    easy = Course.objects.filter(level="easy")
    medium = Course.objects.filter(level="medium")
    hard = Course.objects.filter(level="hard")
    context = {
           "User":request.user,
           "CourseClass":Course.objects.all(),
           "easy":easy,
           "medium":medium,
           "hard":hard,
           "whosOnline":whosOnline,
           "picture": NewUser.objects.get(username=username).picture,
           "score": NewUser.objects.get(username=username).score,
           "news":news
           }
    return render(request, 'homepage/courselist.html', context )
    
def course(request, username, coursename, lessonname):
    CL = CourseLocation.objects.filter(newuser__username=username, course__course_name=coursename)
    l = Lesson.objects.filter(lesson_name=lessonname)
    if len(CL) == 0:
        lesson = Lesson.objects.filter(course__course_name=coursename)[0]
        cl = CourseLocation(newuser=NewUser.objects.get(username=username), course=Course.objects.get(course_name=coursename), islessonornot=True, whichone=lesson.lesson_name)
        cl.save()
    elif CL[0].islessonornot == False and len(l) == 0:
        return HttpResponseRedirect(reverse('homepage:challenge',args=(username,coursename,lessonname,CL[0].whichone)))
    else:
#        cl = CourseLocation.objects.get(newuser__username=username, course__course_name=coursename)
        cl = CL[0]
        if coursename == lessonname:
            lesson = Lesson.objects.get(lesson_name=cl.whichone)
        else:
            lesson = Lesson.objects.get(lesson_name=lessonname)
            cl.whichone = lesson.lesson_name
            cl.islessonornot = True
            cl.save()
    '''
    if coursename == lessonname:
        lesson = Lesson.objects.filter(course__course_name=coursename)[0]
    else:
        lesson = Lesson.objects.get(lesson_name=lessonname)
    '''
    #whosOnline = NewUser.objects.filter(isOnline = True)
    '''
    whosOnline = []
    alluser = NewUser.objects.all()
    for i in alluser:
        if i.username in request.session:
            whosOnline.append(NewUser.objects.get(username = i.username))
    '''
    whosOnline = get_all_logged_in_users()


    p = Progress.objects.filter(newuser__username=username, lesson__lesson_name=lessonname)
    if len(p) == 0:
        Text = ""
        TextNotes = ""
    else:
        Text = p[0].progress_until_now
        TextNotes = p[0].notes
    completeprogresses = Progress.objects.filter(newuser__username=username, is_complete=True)
    completeLesson = [i.lesson for i in completeprogresses]
    completeCprogresses = ChallengeProgress.objects.filter(newuser__username=username, is_complete=True)
    completeChallenges = [i.challenge for i in completeCprogresses]
    context = {"CourseName": coursename,
               "User":request.user,
               "lessonDetail":Lesson.objects.filter(course__course_name=coursename),
               "loadlesson":lesson,
               "name":lesson.lesson_name,
               "whosOnline":whosOnline,
               "isLesson": "true",
               "Text":Text,
               "TextNotes":TextNotes,
               "progress": completeLesson,
               "cprog": completeChallenges,
               "picture": NewUser.objects.get(username=username).picture,
               "score": NewUser.objects.get(username=username).score,
               "Error": lesson.error_message
               }
    return render(request, 'homepage/course.html', context)

def challenge(request, username, coursename, lessonname, challengename):
    challenge = Challenge.objects.get(challenge_name=challengename)
    cl = CourseLocation.objects.get(newuser__username=username, course__course_name=coursename)
    cl.whichone = challenge.challenge_name
    cl.islessonornot = False
    cl.save()
    #whosOnline = NewUser.objects.filter(isOnline = True)
    '''
    whosOnline = []
    alluser = NewUser.objects.all()
    for i in alluser:
        if i.username in request.session:
            whosOnline.append(NewUser.objects.get(username = i.username))
    '''
    whosOnline = get_all_logged_in_users()

    
    p = ChallengeProgress.objects.filter(newuser__username=username, challenge__challenge_name=challengename)
    if len(p) == 0:
        Text = ""
        TextNotes = ""
    else:
        Text = p[0].progress_until_now
        TextNotes = p[0].notes
        
    completeprogresses = Progress.objects.filter(newuser__username=username, is_complete=True)
    completeLesson = [i.lesson for i in completeprogresses]
    completeCprogresses = ChallengeProgress.objects.filter(newuser__username=username, is_complete=True)
    completeChallenges = [i.challenge for i in completeCprogresses]
    context = {"CourseName": coursename,
               "User":request.user,
               "lessonDetail":Lesson.objects.filter(course__course_name=coursename),
               "loadlesson":challenge,
               "name":challenge.challenge_name,
               "whosOnline":whosOnline,
               "isLesson": "false",
               "Text":Text,
               "TextNotes":TextNotes,
               "progress": completeLesson,
               "cprog": completeChallenges,
               "picture": NewUser.objects.get(username=username).picture,
               "score": NewUser.objects.get(username=username).score,
               "Error": challenge.error_message
               }
    return render(request, 'homepage/course.html', context)

def keepprogress(request, username, lessonname):
    #NewUser.objects.create_user(username="OPP", password="123")
    #isLesson = "true"
    if request.POST["haha"] == "true":
        a = Progress.objects.filter(newuser__username = username, lesson__lesson_name = lessonname)
        if len(a) == 0:
            p = Progress(newuser=NewUser.objects.get(username=username), lesson=Lesson.objects.get(lesson_name=lessonname), progress_until_now=request.POST["inputcode"])
            p.save()
        else:
            p = Progress.objects.get(newuser__username = username, lesson__lesson_name = lessonname)
            p.progress_until_now = request.POST["inputcode"]
            p.save()
        if request.POST["isC"] == "true":
            if p.is_complete == False:
                u = NewUser.objects.get(username=username)
                u.score += p.lesson.point_value
                u.save()
            p.is_complete = True
            p.save()
        return HttpResponse("")
    else:
        #return HttpResponse("jlskdjf")
        a = ChallengeProgress.objects.filter(newuser__username = username, challenge__challenge_name = lessonname)
        #return HttpResponse("jlskdjf")
        if len(a) == 0:
            #return HttpResponse("jlskdjf")
            p = ChallengeProgress(newuser=NewUser.objects.get(username=username), challenge=Challenge.objects.get(challenge_name=lessonname), progress_until_now=request.POST["inputcode"])
            p.save()
            #return HttpResponse("jlskdjf")
        else:
            p = ChallengeProgress.objects.get(newuser__username = username, challenge__challenge_name = lessonname)
            p.progress_until_now = request.POST["inputcode"]
            p.save()
        if request.POST["isC"] == "true":
            if p.is_complete == False:
                u = NewUser.objects.get(username=username)
                u.score += p.challenge.point_value
                u.save()
            p.is_complete = True
            p.save()

homepage/templates/homepage/course.html

{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/course_style.css' %}" />

<html>
<head>
    <script src="{% static 'homepage/applozic/js/jquery.min.js'%}"></script>
  


    <title>Athena</title>
    <input type="hidden" id="expected_output" value="{{ loadlesson.expected_output }}"/>
    <script>
    var expected_output = document.getElementById("expected_output").value;
    function getoutput(){   
        output = document.getElementById("output").innerHTML;  
        pattr = expected_output.trim()
        if (output.trim().match(pattr) != null){
            document.getElementById("status").src = "{% static 'homepage/images/check.png' %}";
            document.getElementById("error_message").style.visibility = "hidden";
            return "true";
        }
        else {
            document.getElementById("status").src = "{% static 'homepage/images/x.png' %}";
            document.getElementById("error_message").style.visibility = "visible";
            return "false";
        }
    }
    
    function toggleSidebar(el, other){
        other.style.backgroundColor= "darkorange";
        other.style.color = "white";
        other.style.fontWeight = "300";
        el.style.backgroundColor = "#f9f9f9";
        el.style.color = "grey";
        if (el.name == 'qrs'){
            document.getElementById("who-pane").style.visibility = "hidden";
            document.getElementById("qrs-pane").style.visibility = "visible";
            document.getElementById("qrs-pane").style.height = "auto";
            document.getElementById("who-pane").style.height = "0px";            
        }
        else{
            document.getElementById("qrs-pane").style.visibility = "hidden";
            document.getElementById("who-pane").style.visibility = "visible"; 
            document.getElementById("who-pane").style.height = "auto";
            document.getElementById("qrs-pane").style.height = "0px";                
        }
    }
    </script>    
</head>
<body>
    <buttun style="position:fixed; left:10px; bottom:10px;"><a style="text-decoration: none;" href="{% url 'homepage:courseList' User.username %}">Go Back To Courselist</a></buttun>
    <div class="titleAthena">
        <span><span class="format_logo"><img  src="{% static 'homepage/images/logo.png' %}"></span><span class="Course_Name">{{CourseName}}</span><span class="Lesson_Name">{{ loadlesson.challenge_name }}{{ loadlesson.lesson_name }}</span></span>
        <span class="helloUser">
            <a class="username" href="{% url 'homepage:profile' User.username %}">
                <table style="margin:-5px; padding: 0;">
                    <tr style="margin:0; padding: 0;"><td style="margin:0; padding: 0; text-align: right; vertical-align: bottom;">Welcome, <strong>{{  User.username }}</strong></td><td rowspan="2" style="margin-left: 5px; padding-left:5px;"><img class="img-circle user_pic" src="{% static picture %}" style="height:38;width:38;"></td></tr>
                    <tr style="margin:0; padding: 0;"><td style="margin:0; padding: 0; text-align: right; vertical-align: top;">Score: <strong>{{score}}</strong></td></tr>
                </table>
            </a>
        </span>
    </div>
    <div class="page" id="page">
        <div class="course_nav">
            <ul class="lesson_list">
                {% for i in lessonDetail %}                
                    {% if i.lesson_name == loadlesson.lesson_name %}                   
                        {% if i in progress %}
                            <li class="current_lesson_item"><img class="icon" src= "{% static 'homepage/images/square.png' %}"><a  class="current_lesson_item lesson_complete" href="{% url 'homepage:course' User CourseName i.lesson_name %}">{{ i.lesson_name }}</a><img height="16" width= "16" src = "{% static 'homepage/images/check.png' %}"></li><div name="lines" class="complete_line"> &nbsp;</div>
                        {% else %}                   
                            <li class="current_lesson_item"><img class="icon" src= "{% static 'homepage/images/square.png' %}"><a class="current_lesson_item" href="{% url 'homepage:course' User CourseName i.lesson_name %}">{{ i.lesson_name }}</a></li><div name="lines" class="incomplete_line"> &nbsp;</div>
                        {% endif %}
                    {% else %}              
                        {% if i in progress %}                                  
                            <li class="lesson_item"><img class="icon" src= "{% static 'homepage/images/complete_square.png' %}"><a class="lesson_item lesson_complete" href="{% url 'homepage:course' User CourseName i.lesson_name %}">{{ i.lesson_name }}</a><img height="16" width= "16" src = "{% static 'homepage/images/check.png' %}"></li><div name="lines" class="complete_line"> &nbsp;</div>
                        {% else %}                                
                            <li class="lesson_item"><img class="icon" src= "{% static 'homepage/images/incomplete_square.png' %}"><a class="lesson_item" href="{% url 'homepage:course' User CourseName i.lesson_name %}">{{ i.lesson_name }}</a></li><div name="lines" class="incomplete_line"> &nbsp;</div>
                        {% endif %} 
                    {% endif %}
                    {% for j in i.challenge_set.all %}
                        {% if j.challenge_name == loadlesson.challenge_name and j.id == loadlesson.id %}
                            {% if j in cprog %}
                                <li class="current_lesson_item" ><img class="challenge_icon" src= "{% static 'homepage/images/circles.png' %}"><a class="current_lesson_item lesson_complete" href="{% url 'homepage:challenge' User CourseName i.lesson_name j.challenge_name %}">{{ j.challenge_name }}</a><img height="16" width= "16" src = "{% static 'homepage/images/check.png' %}"></li><div name="lines" class="complete_line">&nbsp;</div>
                            {% else %}
                                <li class="current_lesson_item" ><img class="challenge_icon" src= "{% static 'homepage/images/circles.png' %}"><a class="current_lesson_item" href="{% url 'homepage:challenge' User CourseName i.lesson_name j.challenge_name %}">{{ j.challenge_name }}</a></li><div name="lines" class="incomplete_line">&nbsp;</div>
                            {% endif %}
                        {% else %}
                            {% if j in cprog %}
                                <li class="lesson_item" ><img class="challenge_icon" src= "{% static 'homepage/images/complete_circles.png' %}"><a class="lesson_item lesson_complete" href="{% url 'homepage:challenge' User CourseName i.lesson_name j.challenge_name %}">{{ j.challenge_name }}</a><img height="16" width= "16" src = "{% static 'homepage/images/check.png' %}"></li><div name="lines" class="complete_line">&nbsp;</div>
                            {% else %}
                                <li class="lesson_item" ><img class="challenge_icon" src= "{% static 'homepage/images/incomplete_circles.png' %}"><a class="lesson_item" href="{% url 'homepage:challenge' User CourseName i.lesson_name j.challenge_name %}">{{ j.challenge_name }}</a></li><div name="lines" class="incomplete_line">&nbsp;</div>
                            {% endif %} 
                        {% endif %}
                    {% endfor %}                   
                {% endfor %}
            </ul>
        </div>

        <script>
            function removeLastLine(){
                lines = document.getElementsByName("lines");
                line = lines[lines.length-1]
                line.parentNode.removeChild(line);
            }
            removeLastLine();
        </script>
        
        <div class="lesson_sidebar">
            <button class="sidebar_btn" name="qrs" onclick="toggleSidebar(this, document.getElementById('who'))" id= "qrs" >Script Notes</button>
            <button class="sidebar_btn" name="who" onclick="toggleSidebar(this, document.getElementById('qrs'))" id= "who">Who's Online</button>        
            <p></p>
            <div id="qrs-pane">
                <textarea id="notes" style="position:relative; height: 450px; width:299px; background-color: #ffe4c1; border: none; font-size: 18px;">{{ TextNotes }}</textarea>
            </div>
            <div id="who-pane">
                <table class="online_user_table">
                {% for i in whosOnline %}
                <tr>
                <td class="table_row"><a href="{% url 'homepage:otherprofile' User.username i.username %}"><img class="img-circle" src="{% static i.picture %}" style="height:32;width:32;"%}></a></td>
                <td class="table_row"><a class="online_user" href="{% url 'homepage:chat' User.id User.username i.id i.username %}">{{ i.username }}</a></td>                                
                </tr> 
                {% endfor %}
                </table>
            </div>
        </div>
        
        <script>toggleSidebar(document.getElementById("who"), document.getElementById("qrs"));</script>
        <div class="main_lesson">
            <div class= "lesson_content">
               
                <div id="content_pane">  
                    {% with template_name=loadlesson.content %}
                        {% include template_name %}
                    {% endwith %}
                    <div class= "coding_practice">
                        <p> Write your code here: </p>
                        {% if loadlesson.lesson_name %}
                        {% include './editor.html' with Username=User.username Lessonname=loadlesson.lesson_name isL=isLesson text=Text error=Error %}
                        {% elif loadlesson.challenge_name %}
                        {% include './editor.html' with Username=User.username Lessonname=loadlesson.challenge_name isL=isLesson text=Text error=Error %}
                        {% endif %}
                    </div>
                    <div class="bottom">
                    </div>
                </div> <!-- end content-pane-->
            </div><!-- end lesson_content -->
        </div><!-- end main lesson -->
    </div> 
    {% include './chat.html' %}
</body>

<script>
$( window ).resize(function() {
    var b = $('body').height();
    $('#page').height(b-50);
  $( "#log" ).append( "<div>Handler for .resize() called.</div>" );
});

$( document ).load(function() {
    var b = $('body').height();
    $('#page').height(b-50);
  $( "#log" ).append( "<div>Handler for .resize() called.</div>" );
});
    var b = $('body').height();
    $('#page').height(b-50);
</script>
<script>
    $("#notes").blur(function(){
        $.ajax({
            type:"POST",
            url:"{% url 'homepage:keepnotes' User.username name %}",
            data:{
                haha:{{ isLesson }},
                notes:$("#notes").val(),
                csrfmiddlewaretoken:$("input[name=csrfmiddlewaretoken]").val()
            },
            success:function(){}
        });
    });
</script>

</html>

homepage/templates/homepage/courselist.html
{% load static %}
<html>
<head>
<script>
    function toggleSidebar(el, other){
        other.style.backgroundColor= "darkorange";
        other.style.color = "white";
        other.style.fontWeight = "300";
        el.style.backgroundColor = "#f9f9f9";
        el.style.color = "grey";
        if (el.name == 'qrs'){
            document.getElementById("who-pane").style.visibility = "hidden";
            document.getElementById("qrs-pane").style.visibility = "visible";
            document.getElementById("qrs-pane").style.height = "auto";
            document.getElementById("who-pane").style.height = "0px";            
        }
        else{
            document.getElementById("qrs-pane").style.visibility = "hidden";
            document.getElementById("who-pane").style.visibility = "visible"; 
            document.getElementById("who-pane").style.height = "auto";
            document.getElementById("qrs-pane").style.height = "0px";                
        }
    }
</script>
</head>
<body>
<link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'homepage/course_style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'homepage/course_list_style.css' %}" />

    <div class="titleAthena">
        <span class="format_logo"><img  src="{% static 'homepage/images/logo.png' %}"></span>
        <span class="helloUser">
            <a class="username" href="{% url 'homepage:profile' User.username %}">
                <table style="margin:-5px; padding: 0;">
                    <tr style="margin:0; padding: 0;"><td style="margin:0; padding: 0; text-align: right; vertical-align: bottom;">Welcome, <strong>{{  User.username }}</strong></td><td rowspan="2" style="margin-left: 5px; padding-left:5px;"><img class="img-circle user_pic" src="{% static picture %}" style="height:38;width:38;"></td></tr>
                    <tr style="margin:0; padding: 0;"><td style="margin:0; padding: 0; text-align: right; vertical-align: top;">Score: <strong>{{score}}</strong></td></tr>
                </table>
            </a>
        </span> 
    </div>
    
    <div id="listpage">
        <div class="lesson_sidebar_list" id="timeline">
            <button class="sidebar_btn" name="qrs" onclick="toggleSidebar(this, document.getElementById('who'))" id= "qrs" >Timeline</button>
            <button class="sidebar_btn" name="who" onclick="toggleSidebar(this, document.getElementById('qrs'))" id= "who">Who's Online</button>        
            <p></p>
            <div id="qrs-pane">
                <table>
                    {% for i in news %}
                        {% if i.challenge %}
                            <tr><td><strong>{{ i.newuser.username }}</strong></td><td> finished </td><td><strong>{{ i.challenge.challenge_name }}</strong></td></tr>
                        {% else %}
                            <tr><td><strong>{{ i.newuser.username }}</strong></td><td> finished </td><td><strong>{{ i.lesson.lesson_name }}</strong></td></tr>
                        {% endif %}
                    {% endfor %}
                </table>
            </div>
            <div id="who-pane">
                <table class="online_user_table">
                {% for i in whosOnline %}
                <tr>
                <td class="table_row"><a href="{% url 'homepage:otherprofile' User.username i.username %}"><img class="img-circle" src="{% static i.picture %}" style="height:32;width:32;"%}></a></td>
                <td class="table_row"><a class="online_user" href="{% url 'homepage:chat' User.id User.username i.id i.username %}">{{ i.username }}</a></td>                                
                </tr> 
                {% endfor %}
                </table>
            </div>
        </div>

        <div class="courselist" id="course_list">
            <div class="detail">
                {% include './detaillist.html' with easyc=easy mediumc=medium hardc=hard %}
            </div>
        </div>
        
    </div>
    

<script>toggleSidebar(document.getElementById("who"), document.getElementById("qrs"));</script>
{% include './chat.html' %}
</body>
<script>
$( window ).resize(function() {
    var b = $('body').height();
    $('#listpage').height(b-50);
  $( "#log" ).append( "<div>Handler for .resize() called.</div>" );
});

$( document ).load(function() {
    var b = $('body').height();
    $('#listpage').height(b-50);
  $( "#log" ).append( "<div>Handler for .resize() called.</div>" );
});
var b = $('body').height();
$('#listpage').height(b-50);

var a = $('body').width();

</script>
</html>

homepage/templates/homepage/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}" />

<div class="titleAthena">
    <span float="left"><h1 class="titleText"> ATHENA </h1></span>
    <p class="helloUser">Welcome, <a class="username" href="#">{{ UserName }}</a></p>
</div>

<div class="leftpane">
    <div class="profilePic">
        <img class="img-circle"src="/static/homepage/images/profilepic.png">
        <p> -- {{ UserName }} -- </p>
        <hr>
    </div>
    <div class="listoptions">
        <ul>
            <li><a href="#"><label>>> </label>Course in Progress</a></li>
            <li><a href="{% url 'homepage:startanewcourse'%}"><label>>> </label>Start New Course</a></li>
        </ul>
    </div>
<a class="abutton" href="{% url 'homepage:logoutuser' %}">Logout</a>
</div>

<div class="newsfeed">
    <div class="newscontent">
        <h1> What your class has been up to... </h1>
    </div>
</div>

homepage/templates/homepage/java_intro.html
<p> Welcome to the intro to Java! </p>

homepage/templates/homepage/logout.html
<h1>Please go back to login page!</h1>

<button><a href={% url 'login:index' %}>login</a>></button>